#pragma once

namespace big::meal_data
{
	inline std::map<uint8_t, std::string> meal_buff = {
        {0, "Felyne Polisher"},
        {1, "Felyne Rider"},
        {2, "Felyne Heroics"},
        {3, "Felyne Carver (Hi)"},
        {4, "Felyne Carver (Lo)"},
        {5, "Felyne Medic"},
        {6, "Felyne Black Belt"},
        {7, "Felyne Pyro"},
        {8, "Felyne Specialist"},
        {9, "Felyne Defender (Hi)"},
        {10, "Felyne Defender (Lo)"},
        {11, "Felyne Harvester"},
        {12, "Felyne Sharpshooter"},
        {13, "Lucky Cat"},
        {14, "Felyne Deflector"},
        {15, "Felyne Escape Artist"},
        {16, "Felyne Sprinter"},
        {17, "Felynebacker"},
        {18, "Felyne Weakener"},
        {19, "Felyne Exchanger"},
        {20, "Felyne Riser (Hi)"},
        {21, "Felyne Riser (Lo)"},
        {22, "Felyne Temper"},
        {23, "Felyne Cliffhanger"},
        {24, "Felyne Gripper"},
        {25, "Felyne Iron Carver"},
        {26, "Felyne Lander"},
        {27, "Felyne Bulldozer"},
        {28, "Felyne Foodie"},
        {29, "Felyne Slugger"},
        {30, "Felyne Fat Cat"},
        {31, "Felyne Bombardier"},
        {32, "Felyne Moxie"},
        {33, "Felyne Dungmaster"},
        {34, "Felyne Groomer"},
        {35, "Felyne Fur Coating"},
        {36, "Felyne Acrobat"},
        {37, "Felyne Gamechanger"},
        {38, "Felyne Trainer"},
        {39, "Felyne Booster"},
        {40, "Felyne Feet"},
        {41, "Felyne Fisher"},
        {42, "Cool Cat"},
        {43, "Felyne Insurance"},
        {44, "Felyne Provoker"},
        {45, "Felyne Parting Gift"},
        {46, "Felyne Researcher"},
        {47, "Felyne Weathercat"},
        {48, "Felyne Cleats"},
        {49, "Felyne Tailor"},
        {50, "Felyne Safeguard"},
        {51, "Felyne Gardener"},
        {52, "Felyne Scavenger"},
        {53, "Felyne Zoomaster"},
        {54, "Felyne Biologist"},
        {55, "Felyne Macrozoologist"},
        {56, "Felyne Microzoologist"}
    };
    inline std::map<uint8_t, std::string> skill_category = {
        {0, "Courage"},
        {1, "Resilience"},
        {2, "Vigor"},
        {3, "Acumen"},
        {4, "Artillery"},
        {5, "Perception"},
        {6, "Fortune"}
    };
}