#pragma once
#include "mhw/fwddec.hpp"

namespace big
{
	class weapon_service
	{
	public:
		explicit weapon_service();
		~weapon_service() noexcept;

		void init_melee(MeleeWeapon* wep);
		void init_ranged(RangedWeapon* wep);

		MeleeWeapon* get_melee();
		RangedWeapon* get_ranged();

		_NODISCARD std::string get_melee_elemental();
		_NODISCARD std::string get_melee_hidden_elemental();
		_NODISCARD std::string get_melee_skill();
		_NODISCARD std::string get_ranged_elemental();
		_NODISCARD std::string get_ranged_hidden_elemental();
		_NODISCARD std::string get_ranged_skill();
		std::map<uint8_t, std::string> get_element_data() { return m_element_data; };
		std::map<uint8_t, std::string> get_skill_data() { return m_skill_data; };
	private:
		MeleeWeapon* m_melee_weapon = nullptr;
		RangedWeapon* m_ranged_weapon = nullptr;
		std::map<uint8_t, std::string> m_elderseal = {
			{ 0, "None" },
			{ 1, "Low" },
			{ 2, "Avarage" },
			{ 3, "High" },
		};
		std::map<uint8_t, std::string> m_element_data = {
			{ 0, "None" },
			{ 1, "Fire" },
			{ 2, "Water" },
			{ 3, "Ice" },
			{ 4, "Thunder" },
			{ 5, "Dragon" },
			{ 6, "Poison" },
			{ 7, "Paralysis" },
			{ 8, "Sleep" },
			{ 9, "Blast" }
		};
		std::map<uint8_t, std::string> m_shelling_level = {
			{ 0, "Normal Lvl 1" },
			{ 1, "Normal Lvl 2" },
			{ 2, "Normal Lvl 3" },
			{ 3, "Normal Lvl 4" },
			{ 4, "Normal Lvl 5" },
			{ 5, "Wide Lvl 1" },
			{ 6, "Wide Lvl 2" },
			{ 7, "Wide Lvl 3" },
			{ 8, "Wide Lvl 4" },
			{ 9, "Wide Lvl 5" },
			{ 10, "Long Lvl 1" },
			{ 11, "Long Lvl 2" },
			{ 12, "Long Lvl 3" },
			{ 13, "Long Lvl 4" },
			{ 14, "Long Lvl 5" }
		};
		std::map<uint8_t, std::string> m_phial_type_cb = {
			{ 0, "Impact Phial" },
			{ 1, "Power Element Phial" }
		};
		std::map<uint8_t, std::string> m_skill_data = {
            {0, "None"},
            {1, "Poison Resistance"},
            {2, "Paralysis Resistance"},
            {3, "Sleep Resistance"},
            {4, "Stun Resistance"},
            {5, "Muck Resistance"},
            {6, "Blast Resistance"},
            {7, "Bleeding Resistance"},
            {8, "Iron Skin"},
            {9, "Res Down Protection"},
            {11, "Earplugs"},
            {12, "Windproof"},
            {13, "Tremor Resistance"},
            {14, "Dungmaster"},
            {16, "Effluvial Expert"},
            {17, "Heat Guard"},
            {19, "Attack Boost"},
            {20, "Defense Boost"},
            {21, "Health Boost"},
            {22, "Recovery Up"},
            {23, "Recovery Speed"},
            {24, "Fire Resistance"},
            {25, "Water Resistance"},
            {26, "Ice Resistance"},
            {27, "Thunder Resistance"},
            {28, "Dragon Resistance"},
            {29, "Blight Resistance"},
            {30, "Fire Attack"},
            {31, "Water Attack"},
            {32, "Ice Attack"},
            {33, "Thunder Attack"},
            {34, "Dragon Attack"},
            {35, "Poison Attack"},
            {36, "Paralysis Attack"},
            {37, "Sleep Attack"},
            {38, "Blast Attack"},
            {39, "Normal Attack"},
            {40, "Piercing Shots"},
            {41, "Spread/Power Shots"},
            {42, "Poison Functionality"},
            {43, "Para Functionality"},
            {44, "Sleep Functionality"},
            {45, "Power Functionality"},
            {46, "Blast Functionality"},
            {47, "Free Elem/Ammo Up"},
            {48, "Critical Eye"},
            {49, "Critical Boost"},
            {50, "Weakness Exploit"},
            {51, "Repeat Offender"},
            {52, "Focus"},
            {53, "Power Prolonger"},
            {54, "Handicraft"},
            {55, "Critical Draw"},
            {56, "Partbreaker"},
            {57, "Slugger"},
            {58, "Stamina Thief"},
            {59, "Master Mounter"},
            {60, "Airborne"},
            {61, "Latent Power"},
            {62, "Agitator"},
            {63, "Peak Performance"},
            {64, "Heroics"},
            {65, "Fortify"},
            {66, "Resentment"},
            {67, "Resuscitate"},
            {68, "Horn Maestro"},
            {69, "Capacity Boost"},
            {70, "Special Ammo Boost"},
            {71, "Artillery"},
            {72, "Heavy Artillery"},
            {73, "Marathon Runner"},
            {74, "Constitution"},
            {75, "Leap of Faith"},
            {76, "Stamina Surge"},
            {77, "Hunger Resistance"},
            {78, "Evade Window"},
            {79, "Evade Extender"},
            {80, "Guard"},
            {81, "Quick Sheath"},
            {82, "Wide-Range"},
            {83, "Item Prolonger"},
            {84, "Free Meal"},
            {85, "Speed Eating"},
            {86, "Speed Sharpening"},
            {88, "Bombardier"},
            {90, "Mushroomancer"},
            {91, "Master Fisher"},
            {92, "BBQ Master"},
            {93, "Pro Transporter"},
            {94, "Master Gatherer"},
            {95, "Honey Hunter"},
            {96, "Carving Pro"},
            {97, "Divine Blessing"},
            {98, "Palico Rally"},
            {99, "Botanist"},
            {100, "Geologist"},
            {101, "Maximum Might"},
            {102, "Slinger Capacity"},
            {103, "Stealth"},
            {104, "Flinch Free"},
            {105, "Scoutfly Range Up"},
            {106, "Speed Crawler"},
            {107, "Jump Master"},
            {108, "Sporepuff Expert"},
            {109, "Aquatic Expert"},
            {110, "Afishionado"},
            {111, "Cliffhanger"},
            {112, "Blindsider"},
            {114, "Scholar"},
            {115, "Entomologist"},
            {116, "Effluvia Resistance"},
            {117, "Scenthound"},
            {118, "Forager's Luck"},
            {119, "Detector"},
            {120, "Tool Specialist"},
            {122, "Affinity Sliding"},
            {123, "Elderseal Boost"},
            {124, "Intimidator"},
            {125, "Anjanath Power"},
            {126, "Nergigante Hunger"},
            {127, "Vaal Hazak Vitality"},
            {128, "Rathalos Power"},
            {129, "Diablos Power"},
            {130, "Kirin Blessing"},
            {131, "Pink Rathian Mastery"},
            {132, "Anjanath Will"},
            {135, "Rathalos Mastery"},
            {136, "Diablos Mastery"},
            {137, "Kirin Favor"},
            {138, "Urgaan Protection"},
            {142, "Bazelgeuse Protection"},
            {143, "Teostra Technique"},
            {144, "Kushala Daora Flight"},
            {145, "Xeno'jiiva Divinity"},
            {147, "Zorah Magdaros Mastery"},
            {148, "Hero's Protection"},
            {149, "Guild Guidance"},
            {150, "Commission Guidance"},
            {151, "Legiana Blessing"},
            {152, "Legiana Favor"},
            {153, "Odogaron Power"},
            {154, "Odogaron Mastery"},
            {155, "Bow Charge Plus"},
            {156, "Mind's Eye/Ballistics"},
            {157, "Guard Up"},
            {158, "Protective Polish"},
            {159, "Non-elemental Boost"},
            {160, "Guts"},
            {161, "Hasten Recovery"},
            {162, "Razor Sharp/Spare Shot"},
            {163, "Lunastra Favor"},
            {164, "Soul Of The Dragoon"},
            {165, "Critical Element"},
            {166, "Critical Status"},
            {167, "Witchers Knowledge"},
            {168, "Astera Blessing"},
            {169, "Zinorge Essence"},
            {170, "Tigrex Essence"},
            {171, "Nargacuga Essence"},
            {172, "Brachydios Essence"},
            {173, "Glavenus Essence"},
            {174, "Silver Rathalos Essence"},
            {175, "Gold Rathian Essence"},
            {176, "Shara Ishvalda Divinity"},
            {177, "Namielle Divinity"},
            {178, "Velkhana Divinity"},
            {179, "Ancient Divinity"},
            {180, "Commission Alchemy"},
            {181, "Instructors Guidance"},
            {182, "Anjanath Dominance"},
            {183, "Rathian Essence"},
            {184, "Provoker"},
            {185, "Offensive Guard"},
            {186, "Coalescence"},
            {187, "Safe Landing"},
            {188, "Barioth Hidden Art"},
            {189, "Rathalos Essence"},
            {190, "Diablos Ambition"},
            {191, "Legiana Ambition"},
            {192, "Odogaron Essence"},
            {193, "Uragaan Ambition"},
            {194, "Bazelgeuse Ambition"},
            {195, "Deviljho Essence"},
            {196, "Vaal Soulvein"},
            {199, "Kirin Divinity"},
            {200, "Guild Pride"},
            {201, "Zorah Magdaros Essence"},
            {202, "Lunastra Essence"},
            {203, "Nergigante Ambition"},
            {205, "Bludgeoner"},
            {206, "Adrenaline"},
            {207, "Coldproof"},
            {208, "Rajang Rage"},
            {211, "Safi'jiiva Seal"},
            {212, "Joyful Blessing"},
            {213, "Appreciation Blessing"}
        };
	};

	inline weapon_service* g_weapon_service{};
}